#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf constant/wallFilmRegion
rm -rf constant/extendedFeatureEdgeMesh
rm constant/triSurface/*.eMesh
rm -f *.obj

#------------------------------------------------------------------------------
