#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

# Rotate subject
angle=0
runApplication surfaceTransformPoints constant/triSurface/target_orig.stl constant/triSurface/target.stl -rollPitchYaw "(0 0 $angle)"

./Allmesh
runApplication $application

#------------------------------------------------------------------------------
